- name: "service group present"
  group:
    name: "{{service_group}}"
  become: true

- name: "service user present"
  user:
    name: "{{service_user}}"
    group: "{{service_group}}"
  become: true

- name: "service data directory created"
  file:
    path: "{{service_data_dir}}"
    state: directory
    mode: 0750
    owner:  "{{service_user}}"
    group:  "{{service_group}}"
  become: true

- name: "service binaries downloaded and installed"
  get_url:
    url:  "http://mirrors.jenkins.io/war/{{service_version}}/jenkins.war"
    dest: "{{jenkins_war}}"
    owner: "{{service_user}}"
    group: "{{service_group}}"
    force: no
  become: true

- name: "systemd service config updated"
  template:
    src: "{{service_init_conf}}"
    dest: "/etc/systemd/system/{{service_name}}.service"
    mode: 0640
  become: true
  register: systemd_config

- name: "systemd daemon reload"
  systemd: daemon_reload=yes
  become: true
  when: systemd_config|changed

- name: "user belongs to docker group"
  user:
    name: "{{service_user}}"
    groups: docker
    append: yes
  become: true
  register: docker_group

- name: "restart docker"
  systemd:
    name: docker
    state: restarted
  become: true
  when: docker_group|changed

- name: "service enabled"
  systemd:
    name: "{{service_name}}"
    enabled: yes
  become: true
  
- name: "service started"
  systemd:
    name: "{{service_name}}"
    state: started
  become: true
  register: service_started
  
- name: "restart service"
  systemd:
    name: "{{service_name}}"
    state: restarted
  become: true
  when: (systemd_config|changed or docker_group|changed) and not service_started|changed

