- name: "ssh authorized keys set"
  authorized_key:
    user: "{{item.user}}"
    state: present
    key: "{{lookup('file', item.file)}}"
  with_items:
    - "{{authorized_keys}}"
  become: true