- stat:
    path: "{{ checkout_dir }}/{{ target_file }}.j2"
  register: stat_target_file_j2

- stat:
    path: "{{ checkout_dir }}/{{ target_file }}"
  when: not stat_target_file_j2.exists
  register: stat_target_file

- block:

  - copy:
      src:  "{{ builders_dir }}/{{ target_file }}-{{ lookup('env','POD_NAME') }}.j2"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    register: copy_by_pod_name
    failed_when: false
  
  - copy:
      src:  "{{ builders_dir }}/{{ target_file }}-{{ target_profile }}.j2"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    register: copy_by_target_profile
    when: copy_by_pod_name.failed
    failed_when: false
  
  - copy:
      src:  "{{ builders_dir }}/{{ target_file }}-{{ target_default }}.j2"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    when: copy_by_pod_name.failed
      and copy_by_target_profile.failed|default(true)

  when: not stat_target_file_j2.exists
    and not stat_target_file.exists|default(false)
