- name: "stat {{ checkout_dir }}/{{ target_file }}.j2"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}.j2"
  register: target_file_j2_check

- name: "stat {{ checkout_dir }}/{{ target_file }}"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}"
  when: not target_file_j2_check.stat.exists
  register: target_file_check

- block:


  - stat:
      path: "{{ item }}"
    register: builders_check
    with_items:
      - "{{ builders_dir }}/{{ target_file }}-{{ lookup('env','POD_NAME') }}.j2"
      - "{{ builders_dir }}/{{ target_file }}-{{ target_profile }}.j2"
      - "{{ builders_dir }}/{{ target_file }}-{{ target_default }}.j2"

  - copy:
      src:  "{{ item }}"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    with_items:
      - "{{ bilders_check.stat | | selectattr("path", "defined") | list }}"

  when: not target_file_j2_check.stat.exists
    and not target_file_check.stat.exists|default(false)
