- name: "stat {{ checkout_dir }}/{{ target_file }}.j2"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}.j2"
  register: target_file_j2_check

- name: "stat {{ checkout_dir }}/{{ target_file }}"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}"
  when: not target_file_j2_check.stat.exists
  register: target_file_check

- block:

  - name: "stat {{ builders_dir }}/{{ target_file }}-{{ lookup('env','POD_NAME') }}.j2"
    stat:
      path: "{{ builders_dir }}/{{ target_file }}-{{ lookup('env','POD_NAME') }}.j2"
    register: builder_by_pod_name_check
    
  - name: "stat {{ builders_dir }}/{{ target_file }}-{{ target_profile }}.j2"
    stat:
      path: "{{ builders_dir }}/{{ target_file }}-{{ target_profile }}.j2"
    register: builder_by_target_profile_check

  - name: "stat {{ builders_dir }}/{{ target_file }}-{{ target_default }}.j2"
    stat:
      path: "{{ builders_dir }}/{{ target_file }}-{{ target_default }}.j2"
    register: builder_by_target_default_check

  - copy:
      src:  "{{ item }}"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    with_first_found:
      - builder_by_pod_name_check.stat.path|default(null)
      - builder_by_target_profile_check.stat.path|default(null)
      - builder_by_target_default_check.stat.path|default(null)

  when: not target_file_j2_check.stat.exists
    and not target_file_check.stat.exists|default(false)
