- name: "stat {{ checkout_dir }}/{{ target_file }}.j2"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}.j2"
  register: target_file_j2_check

- name: "stat {{ checkout_dir }}/{{ target_file }}"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}"
  when: not target_file_j2_check.stat.exists
  register: target_file_check

- block:

  - name: "searching order for profile templates"
    stat:
      path: "{{ item }}"
    with_items:
      - "{{ builders_dir }}/{{ target_file }}-{{ lookup('env','POD_NAME') }}.j2"
      - "{{ builders_dir }}/{{ target_file }}-{{ target_profile }}.j2"
      - "{{ builders_dir }}/{{ target_file }}-{{ target_default }}.j2"
    register: builders_check

  - debug:
      msg:
        - "{{ builders_check.results | selectattr('stat.path', 'defined') | list }}"

  - copy:
      src:  "{{ item.stat.path }}"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    with_items:
      - "{{ builders_check.results | selectattr('stat.path', 'defined') | list | first }}"
    loop_control:
      label: "{{ item.stat.path }}"

  when: not target_file_j2_check.stat.exists
    and not target_file_check.stat.exists|default(false)
