- name: "{{ checkout_dir }}/{{ target_file }}.j2 exists?"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}.j2"
  register: target_file_j2_check

- name: "{{ checkout_dir }}/{{ target_file }} exists?"
  stat:
    path: "{{ checkout_dir }}/{{ target_file }}"
  when: not target_file_j2_check.stat.exists
  register: target_file_check

- block:

  - name: "Copy {{ builders_dir }}/{{ target_file }}-{{ lookup('env','POD_NAME') }}.j2"
    copy:
      src:  "{{ builders_dir }}/{{ target_file }}-{{ lookup('env','POD_NAME') }}.j2"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    register: copy_by_pod_name
    failed_when: false
  
  - name: "Copy {{ builders_dir }}/{{ target_file }}-{{ target_profile }}.j2"
    copy:
      src:  "{{ builders_dir }}/{{ target_file }}-{{ target_profile }}.j2"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    register: copy_by_target_profile
    when: copy_by_pod_name.failed
    failed_when: false
  
  - name: "Copy {{ builders_dir }}/{{ target_file }}-{{ target_default }}.j2"
    copy:
      src:  "{{ builders_dir }}/{{ target_file }}-{{ target_default }}.j2"
      dest: "{{ checkout_dir }}/{{ target_file }}.j2"
    when: copy_by_pod_name.failed
      and copy_by_target_profile.failed|default(true)

  when: not target_file_j2_check.stat.exists
    and not target_file_check.stat.exists|default(false)
