- find:
    paths:     "{{ find_paths }}"
    file_type: file
    patterns:  "*.j2"
    recurse:   yes
    excludes:  "{{ find_excludes }}"
  register: find_result

- template:
    src:  "{{ item.path }}"
    dest: "{{ (item.path|splitext)[0] }}"
  with_items: find_result.files