- find:
    paths:     "{{ find_paths }}"
    file_type: file
    recurse:   yes
    use_regex: true
    pattern:  "^.*\\.j2$"
    exclude:  "^({{ find_excludes }}).*$"
  register: find_result

- template:
    src:  "{{ item.path }}"
    dest: "{{ (item.path|splitext)[0] }}"
  with_items:
    - "{{ find_result.files }}"
  loop_control:
    label: "{{ item.path }}"