- find:
    paths:     "{{ checkout_dir }}"
    file_type: file
    patterns:  "*.j2"
    recurse:   yes
    excludes:  "{{ lookup('env','BUILDERS_DIR') }}"
  register: find_result

- template:
    src:  "{{ item.path }}"
    dest: "{{ (item.path|splitext)[0] }}"
  with_items: find_result.files