- find:
    path:     "{{ find_path }}"
    file_type: file
    recurse:   yes
    use_regex: true
    pattern:  "^.*[.]j2$"
    excludes: "^.*echo.*$"
  register: find_result

- template:
    src:  "{{ item.path }}"
    dest: "{{ (item.path|splitext)[0] }}"
  with_items:
    - "{{ find_result.files|select('match', '^'+ find_exclude|replace('.','[.]') +'.*$')|list }}"
  loop_control:
    label: "{{ item.path }}"