- find:
    path:     "{{ find_path }}"
    file_type: file
    recurse:   yes
    use_regex: true
    pattern:  "^.*[.]j2$"
  register: find_result

- debug:
  when: not item.path|contains(find_exclude)
  register: j2_files
  with_items: find_result

- template:
    src:  "{{ item.path }}"
    dest: "{{ (item.path|splitext)[0] }}"
  with_items:
    - "{{ j2_files }}"
  loop_control:
    label: "{{ item.path }}"