- template:
    src:  "{{ item.src }}"
    dest: "{{ (item.src|splitext)[0] }}"
  with_filetree: "{{ checkout_dir }}"
  when: item.state == 'file'
    and (item.src|splitext)[1] == '.j2'
  loop_control:
    loop_var: src
    label: "{{ item.src }}"