- find: >
    path:     "{{ find_path }}"
    file_type: file
    recurse:   yes
    use_regex: true
    pattern:  "^.*\\.j2$"
    exclude:  "^({{ find_exclude }}).*$"
  register: find_result

- debug:
    msg:
      - "^({{ find_exclude }}).*$"

- template:
    src:  "{{ item.path }}"
    dest: "{{ (item.path|splitext)[0] }}"
  with_items:
    - "{{ find_result.files }}"
  loop_control:
    label: "{{ item.path }}"