- block:
  - name: "{{oracle_java_installer}} package removed"
    yum:
      name: "{{oracle_java_installer}}"
      state: absent
    become: true

  - name: "{{java8_openjdk}} package installed"
    package:
      name: "{{java8_openjdk}}"
      state: present
    become: true
  
  when: java_provider == 'openjdk'

- block:
  - name: "{{java8_openjdk}} package removed"
    package:
      name: "{{java8_openjdk}}"
      state: absent
    become: true

  - name: "temporary package directory created"
    tempfile:
      state: directory
    register: temp_directory
    changed_when: false

  - name: "{{oracle_java_installer}} package downloaded"
    get_url:
      url: "{{oracle_java_get_url}}"
      dest: "{{temp_directory.path}}/{{oracle_java_installer}}"
      headers: '"Cookie:oraclelicense=accept-securebackup-cookie'
      force: "{{download_force|default(false)}}"
      mode: +x
    become: true

  - name: "{{oracle_java_installer}} package installed"
    yum:
      name: "{{temp_directory.path}}/{{oracle_java_installer}}"
      state: present
    become: true
  
  when: java_provider == 'oracle'
