- name: "service archive downloaded"
  get_url:
    url:  "https://releases.hashicorp.com/{{service_name}}/{{service_version}}/{{service_name}}_{{service_version}}_linux_amd64.zip"
    dest: "{{artifacts_dir}}/{{service_name}}_{{service_version}}_linux_amd64.zip"
    force: no
  register: service_archive
  become: true

- name: "service binaries installed"
  unarchive:
    src:  "{{artifacts_dir}}/{{service_name}}_{{service_version}}_linux_amd64.zip"
    dest: /usr/local/bin/
    mode: +x
    remote_src: yes
  become: true
  when: service_archive is changed
