- name: "service binaries downloaded and installed"
  unarchive:
    src:  https://releases.hashicorp.com/packer/1.2.3/packer_1.2.3_linux_amd64.zip
    dest: /usr/local/bin/
    mode: +x
    remote_src: yes
  become: true
