- block:
  - name: "rhel optional repository enabled"
    shell: "subscription-manager repos --enable={{rhel_optional_repo}}"
    become: true
    changed_when: false
  when: when: repos_enabled is defined and repos_enabled