- name: "include os variables"
  include_vars: "{{item}}"
  with_first_found:
    - "vars/{{ansible_os_family|lower}}.yml"
  tags: always

- name: "system dirs created"
  file:
    path: "{{item}}"
    recurse: true
    state: directory
  become: true
  with_items:
    - "{{system_dirs}}"

- name: "user dirs created"
  file:
    path: "{{item}}"
    state: directory
    mode: 0750
  with_items:
    - "{{user_dirs}}"

- name: "base packages present"
  package:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - "{{base_packages}}"
  
- name: "sysctl values set"
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    sysctl_set: yes
    reload: yes
  become: true
  with_items:
    - "{{sysctl_entries}}"

- name: "unneeded services disabled and stopped"
  systemd:
    name: "{{item}}"
    enabled: no
    state: stopped
  become: true
  ignore_errors: true
  with_items:
    - "{{disabled_services}}"

- name: "base services enabled and started"
  systemd:
    name: "{{item}}"
    enabled: yes
    masked: no
    state: started
  become: true
  with_items:
    - "{{base_services}}"

