- name: "ansible os package absent"
  package:
    name: ansible
    state: absent
  become: true

- name: "{{ansible_pip_package}} pip package installed"
  pip:
    name: "{{ansible_pip_package}}"
  become: true
