- name: "hostname present in /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{service_bind_ip|default(ansible_default_ipv4.address)}}"
    line: "{{service_bind_ip|default(ansible_default_ipv4.address)}} {{ansible_fqdn}} {{ansible_hostname}}"
    state: present
    backup: yes
  become: true
