- name: "packages updated"
  yum: name=* state=latest update_cache=true
  become: true
  
- name: "reboot required check"
  shell: needs-restarting -r
  ignore_errors: true
  register: reboot_hint
  become: true
  changed_when: false

- name: "machine reboot"
  shell: sleep 4 && shutdown -r now 'Reboot triggered by Ansible'
  async: 1
  poll: 0
  when:  reboot_hint.rc != 0
  register: machine_reboot
  become: true
  
- name: "sleep for 10 seconds"
  wait_for: timeout=10
  delegate_to: localhost
  changed_when: false

- name: "waiting for connection"
  wait_for_connection:
    timeout: "{{ssh_connect_timeout}}"
  when: machine_reboot is defined and machine_reboot is changed

- name: "start services"
  systemd:
    name: "{{item}}"
    state: started
  become: true
  with_items:
    - "{{start_services|default([])}}"
  when: machine_reboot is defined and machine_reboot is changed
