- name: "packages updated"
  yum: name=* state=latest update_cache=true
  become: true
  
- name: "reboot required check"
  shell: needs-restarting -r
  ignore_errors: true
  register: reboot_hint
  become: true
  changed_when: false

- name: "machine reboot"
  shell: sleep 4 && shutdown -r now 'Reboot triggered by Ansible'
  async: 1
  poll: 0
  when:  reboot_hint.rc != 0
  register: machine_reboot
  become: true

- name: "waiting for connection"
  wait_for_connection:
    timeout: "{{ssh_connect_timeout}}"
  when: machine_reboot|defined and machine_reboot|changed

- name: "start services"
  service:
    name: "{{item}}"
    state: started
  become: true
  with_items:
    - "{{start_services|default([])}}"
  when: machine_reboot|defined and machine_reboot|changed
