- name: "read data from consul"
  uri:
    url:    "{{ item| }}?recurse=true"
    method: GET
  failed_when: consul_data.status not in [200,404]
  with_items:
    - "{{ recurse_from }}"
  register: consul_data

- debug:
  - msg:
    - {{ consul_data }}

- name: "write variables in {{ build_env }}"
  lineinfile:
    path:   "{{ build_env }}"
    create: yes
    regexp: '^export {{ item.Key|basename|upper }}='
    line:   'export {{ item.Key|basename|upper }}="{{ item.Value|b64decode }}"'
  with_items: 
    - "{{ consul_data.items.json|default([]) }}"
  loop_control: 
    label: "{{ item.Key|basename|upper }}"