- uri:
    url:    "{{ recurse_url }}?recurse=true"
    method: GET
    status: 200, 404
  register: consul_data

- lineinfile:
    path:   "{{ build_env }}"
    create: yes
    regexp: '^export {{ item.Key|basename|upper }}='
    line:   'export {{ item.Key|basename|upper }}="{{ item.Value|b64decode }}"'
  with_items: 
    - "{{ consul_data.json }}"
  loop_control: 
    label: "{{ item.Key|basename|upper }}"