- name: "service binaries downloaded and installed"
  get_url:
    url:  "https://github.com/stedolan/{{service_name}}/releases/download/{{service_name}}-{{service_version}}/jq-linux64"
    dest: "{{artifacts_dir}}/{{service_name}}-{{service_version}}"
    force: no
  register: service_archive
  become: true

- name: "service binaries installed"
  copy:
    src:  "{{artifacts_dir}}/{{service_name}}-{{service_version}}"
    dest: "/usr/local/bin/{{service_name}}"
    remote_src: yes
    mode: +x
  become: true
  when: service_archive.changed
