- name: "binary is downloaded and installed"
  get_url:
    url:  https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest: /usr/local/bin/jq
    force: "{{download_force}}"
    mode: +x
  become: true

