- name: "ensure jq is installed"
  get_url:
    url:  https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest: /usr/local/bin/jq
    force: no
    mode: +x
  become: true

