- name: "deprecated init.d services disabled and stopped"
  command: "/etc/init.d/{{item}} stop"
  become: yes
  ignore_errors: yes
  with_items:
    - "{{deprecated_init_services}}"

- name: "systemd daemon reload"
  systemd: daemon_reload=yes
  become: true
  changed_when: false

- name: "obsolete files/directories deleted"
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{delete_items}}"
  become: yes

- name: "/etc/profile cleaned"
  lineinfile:
    state: absent
    regexp: "^export {{item}}="
    dest: /etc/profile
  become: true
  with_items:
    - "{{etc_profile_removed}}"

