- name: "kubernetes.repo updated"
  yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  become: true

- name: "kubernetes.repo key imported"
  rpm_key:
    key: "{{item}}"
    state: present
  with_items:
    - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
    - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  become: true

- name: "required packages present"
  yum:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - etcd
    - kubernetes
  become: true

- name: "kubernetes config updated"
  template:
    src: config.j2
    dest: "/etc/kubernetes/config"
  register: kubernetes_config
  become: true

- name: "apiserver config updated"
  template:
    src: apiserver.j2
    dest: "/etc/kubernetes/apiserver"
  register: apiserver_config
  become: true

- name: "etcd config updated"
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  register: etcd_config
  become: true

- name: "kubelet config updated"
  template:
    src: kubelet.j2
    dest: /etc/kubernetes/kubelet
  register: kubelet_config
  become: true

- name: "master-kubeconfig updated"
  template:
    src: master-kubeconfig.yaml.j2
    dest: /etc/kubernetes/master-kubeconfig.yaml
  register: master_kubeconfig
  become: true

- name: "etcd enabled"
  systemd:
    name: etcd
    enabled: yes
  become: true

- name: "etcd started"
  systemd:
    name: etcd
    state: started
  register: etcd_started
  become: true

- name: "restart etcd"
  systemd:
    name: etcd
    state: restarted
  become: true
  when: etcd_config is changed
    and not etcd_started is changed

- name: "apiserver enabled"
  systemd:
    name: kube-apiserver
    enabled: yes
  become: true

- name: "apiserver started"
  systemd:
    name: kube-apiserver
    state: started
  register: apiserver_started
  become: true

- name: "restart apiserver"
  systemd:
    name: kube-apiserver
    state: restarted
  become: true
  when: apiserver_config is changed
    and not apiserver_started is changed

- name: "kube-controller-manager and kube-scheduler enabled and started"
  systemd:
    name: "{{item}}"
    enabled: yes
    state: started
  with_items:
    - kube-controller-manager
    - kube-scheduler
  become: true

- name: "kubelet and kube-proxy enabled"
  systemd:
    name: "{{item}}"
    enabled: yes
  become: true
  with_items:
    - kubelet
    - kube-proxy

- name: "kubelet and kube-proxy started"
  systemd:
    name: "{{item}}"
    state: started
  register: kubelet_started
  become: true
  with_items:
    - kube-proxy
    - kubelet

- name: "restart kubelet and kube-proxy"
  systemd:
    name: "{{item}}"
    state: restarted
  become: true
  with_items:
    - kubelet
    - kube-proxy
  when: (kubelet_config is changed
    or master_kubeconfig is changed)
    and not kubelet_started is changed

