ssh_connect_timeout: 120

user_dirs:
  - "$HOME/profile.d"

system_dirs:
  - /etc/ansible/facts.d

user_ssh_key: "$HOME/.ssh/id_rsa"

service_init_conf: service-systemd.j2

# ansible force option on get_url
download_force: no

# install additional package repositories
repos_enabled: yes

# all targets will run in parallel
serial_value: "100%"

# to replace default dns in resolv.conf with dnsmasq
dnsmasq_supersede: no

# dnsmasq dns servers to use
dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"
