ssh_connect_timeout: 120

user_dirs:
  - "$HOME/profile.d"

system_dirs:
  - /etc/ansible/facts.d

user_ssh_key: "$HOME/.ssh/id_rsa"

service_init_conf: service-systemd.j2

download_force: no

repos_enabled: yes

dnsmasq_supersede: no

dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"
