ssh_connect_timeout: 120

user_dirs:
  - "$HOME/profile.d"

system_dirs:
  - /etc/ansible/facts.d

user_ssh_key: "$HOME/.ssh/id_rsa"

service_init_conf: service-systemd.j2
service_bind_ip: $IPV4_PRIMARY_IP_ADDR

ipv4_main_interface: "$(ip route get 8.8.8.8 | head -1 | perl -lne 'print $2 if /(\\w+) dev (\\w+)/')"
ipv4_main_ip_addr: "$(ip -f inet addr show $IPV4_PRIMARY_INTERFACE | grep -Po 'inet \\K[\\d.]+')"

dnsmasq_supersede: no
repos_enabled: yes
