- name: "ensure required system directories are created"
  file:
    path: "{{ item }}"
    recurse: true
    state: directory
  become: true
  with_items:
    - "{{ system_dirs }}"

- name: "ensure required user directories are created"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ user_dirs }}"

- name: "check if ssh key exists at {{ user_ssh_key }}" 
  stat: path="{{ user_ssh_key }}"
  register: ssh_key_check

- name: "generate ssh key {{ user_ssh_key }}"
  shell: "ssh-keygen -b 2048 -t rsa -C 'ansible' -N '' -f {{ user_ssh_key }}"
  when: ssh_key_check.stat.exists == false

- name: "ensure required packages are installed"
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ packages }}"

- name: ensure needed services are enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  become: true
  with_items:
    - "{{ on_services }}"
