- hosts: all
  gather_facts: no

  roles:
    - role: copy-profile-template
      target_file:    "docker-compose.yml"
      target_profile: "{{lookup('env','COMPOSE_PROFILE')|default('default',true)}}"
  
    - role: copy-profile-template
      target_file:    "Dockerfile"
      target_profile: "{{lookup('env','BUILD_PROFILE')|default('default',true)}}"

    - role: copy-profile-template
      target_file:    "nomad-job.hcl"
      target_profile: "{{lookup('env','DEPLOY_PROFILE')|default('default',true)}}"
