FROM gradle:4.7-jdk8 as BUILDER
COPY --chown=gradle:gradle . /home/gradle/{{lookup('env','POD_NAME')}}
WORKDIR /home/gradle/{{lookup('env','POD_NAME')}}
RUN gradle build \
&& gradle sonarqube -Dsonar.host.url=http://sonar.service.consul:9999/sonar -Dsonar.login=34119ab9b578e0c2336ea2a09fe1fb2855d4257b

FROM openjdk:8u171-jre-slim
RUN useradd --no-create-home --no-log-init --system app
USER app
COPY --from=BUILDER /home/gradle/{{lookup('env','POD_NAME')}}/build/libs/*.jar /
WORKDIR /
CMD ["/bin/sh", "-c", "java -jar *.jar"]