FROM gradle:4.7-jdk8 as BUILDER
COPY --chown=gradle:gradle . /home/gradle/{{lookup('env','POD_NAME')}}
WORKDIR /home/gradle/{{lookup('env','POD_NAME')}}
RUN echo nameserver {{lookup('env','JENKINS_IP_ADDR')}} > /etc/resolv.conf \
&& gradle build \
&& gradle sonarqube -Dsonar.host.url=http://sonar.service.consul:9999/sonar -Dsonar.login=cf02f4f665ec2c9aced87ad7fb14b2997685a7d5

FROM openjdk:8u171-jre-slim
RUN useradd --no-create-home --no-log-init --system app
USER app
COPY --from=BUILDER /home/gradle/{{lookup('env','POD_NAME')}}/build/libs/*.jar /
WORKDIR /
CMD ["/bin/sh", "-c", "java -jar *.jar"]