FROM maven:3.5-jdk-8-slim as BUILDER
RUN mkdir -p /build/{{lookup('env','POD_NAME')}} \
&& chown -R nobody:nogroup /build/{{lookup('env','POD_NAME')}}
COPY --chown=nobody:nogroup . /build/{{lookup('env','POD_NAME')}}
WORKDIR /build/{{lookup('env','POD_NAME')}}
RUN mvn --batch-mode -Dmaven.test.failure.ignore clean package

FROM openjdk:8u171-jre-slim
RUN useradd --no-create-home --no-log-init --system java
USER java
COPY --from=BUILDER /build/{{lookup('env','POD_NAME')}}/target/*.jar /
WORKDIR /
USER nobody
CMD ["/bin/sh", "-c", "java -jar *.jar"]