FROM gradle:4.7-jdk8 as BUILDER
COPY --chown=gradle:gradle . /home/gradle/{{lookup('env','POD_NAME')}}
WORKDIR /home/gradle/{{lookup('env','POD_NAME')}}
RUN gradle build

FROM openjdk:8u171-jre-slim
RUN useradd --no-create-home --no-log-init --system java
USER java
COPY --from=BUILDER /home/gradle/{{lookup('env','POD_NAME')}}/build/libs/*.jar /
WORKDIR /
CMD ["/bin/sh", "-c", "java -jar *.jar"]