- hosts: all
  gather_facts: no

  roles:
    - role: profile-templates
      target_file:    "docker-compose.yml"
      target_default: "default"
      target_profile: "{{lookup('env','COMPOSE_PROFILE')|default('none',true)}}"
  
    - role: profile-templates
      target_file:    "Dockerfile"
      target_default: "default"
      target_profile: "{{lookup('env','BUILD_PROFILE')|default('none',true)}}"

    - role: profile-templates
      target_file:    "nomad-job.hcl"
      target_default: "default"
      target_profile: "{{lookup('env','DEPLOY_PROFILE')|default('none',true)}}"
