service_name:     nomad
service_version:  0.7.1
service_user:     "{{service_name}}"
service_group:    "{{service_name}}"
service_data_dir: "/usr/local/share/{{service_name}}"
service_conf_dir: "/etc/{{service_name}}.d"
service_env: {
  GOMAXPROCS:     "${GOMAXPROCS:-4}"
}
service_exec:     "/usr/local/bin/{{service_name}}"
service_args:     "agent -config={{service_conf_dir}}"

service_meta: {
  foo:            "bar"
}
