- name: "include variables"
  include_vars: "{{item}}"
  with_first_found:
    - "vars/{{ansible_distribution|lower}}.yml"
  tags: always

- name: "yum - docker repository added"
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  become: true
  when: ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos'

- name: "docker group created"
  group:
    name: docker
  become: true
  register: docker_groups_task

- name: "docker packages installed"
  package:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - "{{docker_packages}}"

- name: "{{ansible_user_id}} appended to docker group"
  user:
    name: "{{ansible_user_id}}"
    groups: docker
    append: yes
  become: true
  with_items:
    - "{{docker_groups}}"
  notify:
    - restart docker

- name: "net.ipv4.ip_forward is enabled"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
  become: true

- name: "shell profile scripts are in place"
  copy:
    src: "{{item}}"
    dest: "{{ansible_env.HOME}}/profile.d/"
  with_fileglob: "{{role_path}}/files/profile.d/*"
  tags: env

- name: "docker service enabled and started"
  service:
    name: docker
    enabled: yes
    state: started
  become: true
