- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  roles:
    - role: alive
    - role: gather-facts
    - role: debug
    - role: check-sudo
    - role: systemd-setenv
    - role: base
    - role: swap
    - role: jq
