- hosts: all
  gather_facts: no
  serial: "100%"

  roles:
    - role: gather-facts
    
    - role: consul
      vars:
        service_mode: server
    
    - role: vault
      vars:
        service_mode: server
