- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  roles:
    - role: gather-facts
      tags: always
    - role: debug
      tags: always
    - role: dnsmasq
      dns_servers:
        - "/consul/127.0.0.1#8600"
        - "172.28.27.162"
        - "172.28.27.163"
      dnsmasq_supersede: yes
