- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  roles:
    - role: alive
    - role: consul
    - role: nomad
    - role: vault
    - role: packer
    - role: terraform
    - role: terragrunt
