- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  roles:
    - role: alive
    - role: consul
      service_install: false
    - role: nomad
      service_install: false
    - role: vault
      service_install: false
    - role: packer
