- hosts: all
  gather_facts: no
  serial: "{{ serial_value | default(1) }}"

  roles:
    - role: alive
    - role: gather-facts
    - role: check-sudo
    - role: ansible
    - role: docker
    - role: docker-compose
    - role: jenkins
    - role: user-ssh-key
      run_as: jenkins
