- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  roles:
    - role: alive
    - role: gather-facts
    - role: check-sudo
    - role: ansible
    - role: docker
    - role: docker-compose
    - role: terraform
    - role: terragrunt
    - role: packer
    - role: mo
    - role: jq
    - role: pumba
    - role: java8-openjdk
    - role: jenkins
    - role: user-ssh-key
      run_as: jenkins
