- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  vars:
    - repos_enabled: true

  roles:
    - role: alive
    - role: gather-facts
    - role: check-sudo
    - role: housekeeping
    - role: base
    - role: dnsmasq
      dnsmasq_supersede: yes
      dns_servers:
        - "/consul/127.0.0.1#8600"
        - "8.8.8.8"
        - "8.8.4.4"    
    - role: ansible
    - role: terraform
    - role: terragrunt
    - role: mo
    - role: jq
    - role: java8-openjdk
    - role: jenkins
    - role: user-ssh-key
      run_as: jenkins
