- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  roles:
    - role: alive
    - role: gather-facts
    - role: check-sudo
    - role: housekeeping
    - role: base
    - role: dnsmasq
      dnsmasq_supersede: yes
      dns_servers:
        - "/consul/172.28.16.61"
        - "/consul/172.28.16.62"
        - "172.28.27.162"
        - "172.28.27.163"
    - role: jq
    - role: docker
    - role: pumba
    - role: consul
      service_mode: client
    - role: nomad
      service_mode: client