- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  vars:
    - repos_enabled: true

  tasks:
    - include_role:
        name: alive

    - include_role:
        name: gather-facts

    - include_role:
        name: check-sudo

    - block:
      - include_role:
          name: housekeeping

      - include_role:
          name: base

      - include_role:
          name: dnsmasq
        vars:
          dnsmasq_supersede: no
          dns_servers:
            - "/consul/192.0.2.255#8600"

      - include_role:
          name: jq

      - include_role:
          name: docker

      - include_role:
          name: pumba

      - include_role:
          name: setup-completed
      when: not ansible_local.setup_completed|default(false) or force_setup|default(false)

    - include_role:
        name: consul
      vars:
        service_mode: client

    - include_role:
        name: nomad
      vars:
        service_mode: client
        service_meta: {
          foo: "bar"
        }
