- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  vars:
    - repos_enabled: true

  tasks:
    - include_role:
        name: alive
    - include_role:
        name: gather-facts
    - include_role:
        name: check-sudo

    - block:
      - include_role:
          name: housekeeping
      - include_role:
          name: base
      - include_role:
          name: dnsmasq
        vars:
          - dnsmasq_supersede: yes
          - dns_servers:
            - "8.8.8.8"
            - "8.8.4.4"
      - include_role:
          name: jq
      - include_role:
          name: docker
      - include_role:
          name: pumba
      when: not ansible_local.setup_completed|default(false) or force_setup|default(false)

    - include_role:
        name: consul
      vars:
        - service_install: true
        - service_mode: client
    - include_role:
        name: nomad
      vars:
        - service_install: true
        - service_mode: client
        - service_meta: {
            foo: "bar"
          }
