- hosts: all
  gather_facts: no

  roles:
    - role: alive
    - role: gather-facts
    - role: check-sudo
    - role: housekeeping
    - role: user-ssh-key
    - role: base
    - role: dnsmasq
      dnsmasq_supersede: yes
      dns_servers:
        - "8.8.8.8"
        - "8.8.4.4"
    - role: ansible
    - role: docker
    - role: docker-compose
    - role: pumba
    - role: jq
    - role: consul
      service_install: false
    - role: nomad
      service_install: false
    - role: vault
      service_install: false
    - role: packer
    - role: terraform
    - role: terragrunt
    - role: workstation
