- hosts: all
  gather_facts: no

  roles:
    - role: alive
    - role: gather-facts
    - role: debug
    - role: check-sudo
    - role: housekeeping
    - role: user-ssh-key
    - role: base
    - role: hostname
    - role: os-update
    - role: dnsmasq
      dns_servers:
        - 8.8.8.8
        - 8.8.4.4
      dnsmasq_supersede: yes
    - role: ansible
    - role: docker
    - role: docker-compose
    - role: hashicorp-tools
    - role: jq
    - role: workstation
