- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  vars:
    - repos_enabled: true

  tasks:
    - include_role:
        name: alive

    - include_role:
        name: gather-facts

    - include_role:
        name: check-sudo

    - block:
      - include_role:
          name: housekeeping

      - include_role:
          name: base-minimal

      - include_role:
          name: dnsmasq

      - include_role:
          name: ansible

      - include_role:
          name: consul
        vars:
          service_mode: dev

      - include_role:
          name: mo

      - include_role:
          name: jq

      - include_role:
          name: setup-completed
      when: not ansible_local.setup_completed|default(false) or force_setup|default(false)

    - include_role:
        name: java8-jre
      vars:
        java_provider: oracle

    - include_role:
        name: jenkins

    - include_role:
        name: user-ssh-key
      vars:
        run_as: jenkins
