- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  vars:
    - repos_enabled: true

  tasks:
    - include_role:
        name: alive
    - include_role:
        name: gather-facts
    - include_role:
        name: check-sudo

    - block:
      - include_role:
          name: housekeeping
      - include_role:
          name: base
      - include_role:
          name: dnsmasq
        vars:
          dnsmasq_supersede: yes
          dns_servers:
            - "/consul/127.0.0.1#8600"
            - "8.8.8.8"
            - "8.8.4.4"
      - include_role:
          name: jq
      - include_role:
          name: setup-completed
      when: not ansible_local.setup_completed|default(false) or force_setup|default(false)

    - include_role:
        name: consul
      vars:
        service_mode: server
    - include_role:
        name: nomad
      vars:
        service_mode: server
