- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  vars:
    - repos_enabled: true

  roles:
    - role: alive
    - role: gather-facts
    - role: check-sudo
    - role: housekeeping
    - role: base
    - role: dnsmasq
      dnsmasq_supersede: yes
      dns_servers:
        - "/consul/127.0.0.1#8600"
        - "8.8.8.8"
        - "8.8.4.4"
    - role: jq
    - role: consul
      service_mode: server
    - role: nomad
      service_mode: server
