- hosts: all
  gather_facts: no

  vars:
    - repos_enabled: true

  roles:
    - role: alive
    - role: gather-facts
    - role: check-sudo
    - role: housekeeping
    - role: user-ssh-key
    - role: base
    - role: hostname
    - role: dnsmasq
      dnsmasq_resolv: supersede
      dns_servers:
        - "/consul/127.0.0.1#8600"
        - "8.8.8.8"
        - "8.8.4.4"
    - role: ansible
    - role: docker
    - role: docker-compose
    - role: pumba
    - role: jq
    - role: consul
    - role: nomad
    - role: vault
    - role: packer
    - role: terraform
    - role: terragrunt
    - role: workstation
    