- hosts: all
  gather_facts: no
  serial: "{{serial_value|default(1)}}"

  vars:
    - repos_enabled: true

  tasks:
    - include_role:
        name: alive
    - include_role:
        name: gather-facts
    - include_role:
        name: check-sudo
    - include_role:
        name: vault