- hosts: all
  gather_facts: no

  roles:
    - role: alive
    - role: gather-facts
    - role: debug
    - role: check-sudo
    - role: user-ssh-key
    - role: base
    - role: dnsmasq
      dns_servers:
        - 8.8.8.8
        - 8.8.4.4
    - role: ansible
    - role: docker
    - role: docker-compose
    - role: workstation
