service_name:     consul
service_version:  1.0.6
service_user:     "{{service_name}}"
service_group:    "{{service_name}}"
service_data_dir: "/usr/local/share/{{service_name}}"
service_conf_dir: "/etc/{{service_name}}.d"
service_env: {
  GOMAXPROCS:     "${GOMAXPROCS:-2}"
}
service_exec:     "/usr/local/bin/{{service_name}}"
service_args:     "agent -config-dir={{service_conf_dir}}"
