etc_profile_vars: []

pam_limits:
  - domain: '*'
    type: '-'
    limit: nofile
    value: 64000
    
sysctl_entries:
  - name: net.core.somaxconn
    value: 1024
  - name: net.core.netdev_max_backlog
    value: 5000
  - name: net.core.rmem_max
    value: 16777216
  - name: net.core.wmem_max
    value: 16777216
  - name: net.ipv4.tcp_wmem
    value: '4096 12582912 16777216'
  - name: net.ipv4.tcp_rmem
    value: '4096 12582912 16777216'
  - name: net.ipv4.tcp_max_syn_backlog
    value: 8096
  - name: net.ipv4.tcp_slow_start_after_idle
    value: 0
  - name: net.ipv4.tcp_tw_reuse
    value: 1
  - name: net.ipv4.ip_local_port_range
    value: '10240 65535'
  - name: vm.swappiness
    value: 10