service_name:     vault
service_version:  0.9.5
service_user:     "{{ service_name }}"
service_group:    "{{ service_name }}"
service_data_dir: "/usr/local/share/{{ service_name }}"
service_conf_dir: "/etc/{{ service_name }}.d"
service_env: {
  PATH:           "/usr/local/bin:$PATH",
  GOMAXPROCS:     "${GOMAXPROCS:-2}",
  IPV4_MAIN_IF:   "{{ ipv4_main_interface }}",
  IPV4_MAIN_IP:   "{{ ipv4_main_ip }}"
}
service_exec:     "/usr/local/bin/{{ service_name }}"
service_args:     "server -config={{ service_conf_dir }}"
