service_name:     vault
service_version:  1.0.1
service_user:     "{{service_name}}"
service_group:    "{{service_name}}"
service_data_dir: "/usr/local/share/{{service_name}}"
service_conf_dir: "/etc/{{service_name}}.d"
service_env: {
  GOMAXPROCS:     "${GOMAXPROCS:-2}",
}
service_exec:     "/usr/local/bin/{{service_name}}"
service_args_def: "server -config={{service_conf_dir}}"
service_args_dev: "server -dev"
service_args:     "{{ service_args_dev if service_mode == 'dev' else service_args_def }}"
