- name: "binary is downloaded and installed"
  get_url:
    url:  https://github.com/gruntwork-io/terragrunt/releases/download/v0.14.9/terragrunt_linux_amd64
    dest: /usr/local/bin/terragrunt
    force: "{{download_force|default(false)}}"
    mode: +x
  become: true

